version: "3"
services:
  app:
    image: node:14
    command: ["npm", "run", "dev"]
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MONGO_URI=${MONGO_URI}
    ports:
      - "80:80"
    volumes:
      - ./app:/usr/src/app
