openapi: 3.0.0
info:
  title: SmartHydroGas Backend Docs
  version: 1.0.0
  description: Documentation of all routes of SmartHydroGas Project.
servers:
  - url: http://localhost:80
    description: Local server
tags:
  - name: Users
    description: Users routes
paths:
  /createAccount:
    post:
      summary: Cria uma conta no site.
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                  description: Primeiro nome do usuário.
                  example: Lucas
                lastName:
                  type: string
                  description: Sobrenome do usuário.
                  exemple: Souza
                cpf:
                  type: string
                  description: CPF do usuário.
                  exemple: 77777777777
                address:
                  type: string
                  description: Endereço do usuário.
                  exemple: Rua dos usuários, 68, Centro
                email:
                  type: string
                  description: Email do usuário.
                  exemple: user@gmail.com
                password:
                  type: string
                  description: Senha do usuário.
                  exemple: mudar123
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
  /users/{id}:
    get:
      summary: Get user by ID
      tags:
        - Users
      parameters:
        - in: path
          name: id
          required: true
          description: The user ID
          schema:
            type: string
      responses:
        "200":
          description: The user data
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
        "404":
          description: User not found
